name = "AbstractModel"
uuid = "0f14bbd8-593a-4bbc-8ec0-b728f6a4d88c"
authors = ["dsdennis"]
version = "0.1.0"

[deps]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SpineInterface = "0cda1612-498a-11e9-3c92-77fa82595a4f"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
